[package]
name = "words"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "words"
path = "main.rs"

[profile.dev]
opt-level = 3

[lib]
name = "words"
path = "words.rs"
